# **Word Embedding Techniques using Embedding Layer in Keras**

In [1]:
import tensorflow as tf
print(tf.__version__)

2023-01-21 05:58:03.280651: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-01-21 05:58:04.348702: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2023-01-21 05:58:04.348750: I tensorflow/compiler/xla/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2023-01-21 05:58:07.413081: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory
2023-

2.11.0


In [2]:
sentences = ['Marvel series is my favourite movie',
              'the cup of coffee',
              'the cup of tea',
              'I am working as subject matter expert',
              'I am a good developer',
              'the cat is eating the food',
              'your lectures are good']

In [3]:
sentences

['Marvel series is my favourite movie',
 'the cup of coffee',
 'the cup of tea',
 'I am working as subject matter expert',
 'I am a good developer',
 'the cat is eating the food',
 'your lectures are good']

In [4]:
voc_size = 500

In [5]:
from tensorflow.keras.preprocessing.text import one_hot

onehot_repr = [one_hot(words,voc_size) for words in sentences] 

In [6]:
onehot_repr

[[30, 215, 281, 141, 190, 406],
 [497, 477, 307, 198],
 [497, 477, 307, 137],
 [196, 59, 469, 302, 83, 189, 80],
 [196, 59, 248, 341, 385],
 [497, 436, 281, 380, 497, 487],
 [224, 60, 463, 341]]

In [7]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
sent_length = 8
embedded_docs = pad_sequences(onehot_repr, padding='pre', maxlen=sent_length)

In [9]:
print(embedded_docs)

[[  0   0  30 215 281 141 190 406]
 [  0   0   0   0 497 477 307 198]
 [  0   0   0   0 497 477 307 137]
 [  0 196  59 469 302  83 189  80]
 [  0   0   0 196  59 248 341 385]
 [  0   0 497 436 281 380 497 487]
 [  0   0   0   0 224  60 463 341]]


In [10]:
dim = 10

In [11]:
model = Sequential()
model.add(Embedding(voc_size, 10, input_length=sent_length))
model.compile('adam','mse')

2023-01-21 05:58:11.339417: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2023-01-21 05:58:11.340269: W tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:265] failed call to cuInit: UNKNOWN ERROR (303)
2023-01-21 05:58:11.340324: I tensorflow/compiler/xla/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (instance-5.us-east1-b.c.deloitte-team1.internal): /proc/driver/nvidia/version does not exist
2023-01-21 05:58:11.342966: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             5000      
                                                                 
Total params: 5,000
Trainable params: 5,000
Non-trainable params: 0
_________________________________________________________________


In [13]:
print(model.predict(embedded_docs))

1/1 [==============================] - 0s 245ms/step
[[[-0.01292511  0.01650948  0.04098852 -0.00535557  0.01094609
    0.00756294 -0.02065355  0.04931127 -0.03263747 -0.0018859 ]
  [-0.01292511  0.01650948  0.04098852 -0.00535557  0.01094609
    0.00756294 -0.02065355  0.04931127 -0.03263747 -0.0018859 ]
  [ 0.01261166  0.04211699 -0.04540818 -0.01785394 -0.03458488
   -0.03611199  0.04852379  0.00732354 -0.00081839  0.00038292]
  [-0.0480465   0.02407986 -0.0460626   0.03671534 -0.00720156
    0.0181661   0.0295879   0.03588152 -0.00221718  0.03004142]
  [ 0.03366678  0.01976874 -0.04832819 -0.02825772  0.02014418
   -0.01624667  0.03479642  0.03706584  0.03809022 -0.00018489]
  [ 0.00932177 -0.0441368  -0.03424969 -0.03222843 -0.0224482
    0.01235925  0.0215647   0.03407158 -0.04137231  0.01671628]
  [-0.01479749  0.01231532  0.011304   -0.00766896 -0.03309841
   -0.03482059  0.03719313  0.00128601  0.04087922 -0.00012951]
  [ 0.01685368  0.03222669 -0.00933317 -0.00698788  0.04344

In [14]:
print(embedded_docs[0])

[  0   0  30 215 281 141 190 406]


In [15]:
print(model.predict(embedded_docs)[0])

1/1 [==============================] - 0s 26ms/step
[[-0.01292511  0.01650948  0.04098852 -0.00535557  0.01094609  0.00756294
  -0.02065355  0.04931127 -0.03263747 -0.0018859 ]
 [-0.01292511  0.01650948  0.04098852 -0.00535557  0.01094609  0.00756294
  -0.02065355  0.04931127 -0.03263747 -0.0018859 ]
 [ 0.01261166  0.04211699 -0.04540818 -0.01785394 -0.03458488 -0.03611199
   0.04852379  0.00732354 -0.00081839  0.00038292]
 [-0.0480465   0.02407986 -0.0460626   0.03671534 -0.00720156  0.0181661
   0.0295879   0.03588152 -0.00221718  0.03004142]
 [ 0.03366678  0.01976874 -0.04832819 -0.02825772  0.02014418 -0.01624667
   0.03479642  0.03706584  0.03809022 -0.00018489]
 [ 0.00932177 -0.0441368  -0.03424969 -0.03222843 -0.0224482   0.01235925
   0.0215647   0.03407158 -0.04137231  0.01671628]
 [-0.01479749  0.01231532  0.011304   -0.00766896 -0.03309841 -0.03482059
   0.03719313  0.00128601  0.04087922 -0.00012951]
 [ 0.01685368  0.03222669 -0.00933317 -0.00698788  0.04344222  0.01818917
